version: 1.0.{build}
image: Visual Studio 2017
configuration: Release

branches:
  only:
    - master

build_script:
  ci-build.cmd

install:
- ps: >-
    cd src

    nuget restore Vortice.Mathematics.sln

    $env:VORTICE_BUILD_NUMBER = ([int]$env:APPVEYOR_BUILD_NUMBER).ToString("000")
   
    $env:VORTICE_VERSION_SUFFIX = "pre$env:VORTICE_BUILD_NUMBER"

    $env:appveyor_nuget_push = 'false'

    if(-Not $env:APPVEYOR_PULL_REQUEST_NUMBER) {
      if($env:appveyor_repo_tag -eq 'True') {
    	  if($env:appveyor_repo_tag_name -match '^v[0-9]') {
           $env:appveyor_nuget_push = 'true'
           $env:VORTICE_VERSION_SUFFIX = ""
        }
    	  if($env:appveyor_repo_tag_name -eq 'latest') {
           $env:appveyor_nuget_push = 'true'
        }        
      }
    }

build:
  project: src/Vortice.Mathematics.sln
  verbosity: minimal

before_package:
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release Vortice.Mathematics/Vortice.Mathematics.csproj
- cmd: msbuild /t:pack /p:VersionSuffix="%VORTICE_VERSION_SUFFIX%" /p:Configuration=Release Vortice.Mathematics.PackedVector/Vortice.Mathematics.PackedVector.csproj

artifacts:
- path: bin\Release\Packages\*.nupkg
  name: Nugets Artifacts

nuget:
  project_feed: true

deploy:
- provider: NuGet
  api_key:
    secure: 7kKL2l4dDfYB1nulVfUJYAtx43lETKMX+fMrnOwO9wljBNXanlMubrTSjgpaWnzn
  on:
    appveyor_nuget_push: true
  artifact: Nugets Artifacts 
